### ISSUE TITLE
error while running simple example

### ISSUE THREAD

**Issue by imalkov82** [FRosner/drunken-data-quality#111]
Hi 

I using jupyter that is running above pyspark.
First I installed pyddq with:
pip2.7 install pyddq==3.2.1 (python2.7)

Then I execute simple example that ended with error (see attached pic).
What I missing?

B.R
Igor

![pyddq_error](https://cloud.githubusercontent.com/assets/5299802/18086330/0b1b0c6e-6eb8-11e6-8bdb-41296f081353.PNG)

**Comment by Gerrrr** [comment]
Hi @imalkov82 !

Did you pass the jar to `--driver-class-path`?
https://github.com/FRosner/drunken-data-quality#python-api-1

**Comment by imalkov82** [comment]
Thanks for your response!

No ...
Can you give me the location where I can download the drunken-data-quality_2.10-x.y.z.jar?

Igor

**Comment by imalkov82** [comment]
Probably is it:
https://github.com/FRosner/drunken-data-quality/releases

Thanks!

**Comment by Gerrrr** [comment]
You can download the jar from the [release section](https://github.com/FRosner/drunken-data-quality/releases). 

Thanks for the feedback, I'll create a patch to check if the jar is available in the class path.

**Comment by FRosner** [comment]
How difficult is it to provide this check @Gerrrr? Shall we put it into the 4.1.0 release?

**Comment by Gerrrr** [comment]
It is almost done, I only have a couple of tests to fix. Yep, let's put it into the 4.1.0.
