### ISSUE TITLE
Column instance with the python app

### ISSUE THREAD

**Issue by Lucindo06** [FRosner/drunken-data-quality#116]
Column instance with the python version is not working.
When I try to execute this code : 

%pyspark
from pyddq.core import Check
from pyddq.reporters import ZeppelinReporter

df = sqlContext.createDataFrame([(1, "a"), (1, None), (3, "c")])
check = Check(df)
reporter = ZeppelinReporter(z)
check.satisfies(df._1 > 0).run([reporter])

I get : 
_TypeError: 'Column' object is not callable_

**Comment by FRosner** [comment]
@Gerrrr any thoughts? What was the reason why we didn't implement?

**Comment by Gerrrr** [comment]
Originally I did not figure how to convert `pyspark.sql.Column` into scala's column. It is implemented in https://github.com/FRosner/drunken-data-quality/pull/118 now.
