### ISSUE TITLE
access check results in dataframe

### ISSUE THREAD

**Issue by jamiegeyer** [FRosner/drunken-data-quality#150]
Is it possible to just push check results to a dataframe, then I can do whatever I want with it?

**Comment by FRosner** [comment]
There was https://github.com/FRosner/drunken-data-quality/issues/95 and even some discussions around that (https://github.com/FRosner/drunken-data-quality/pull/99) but it was never finished.

Independently of that you can programatically access the check results as described here: https://github.com/FRosner/drunken-data-quality#unit-tests

**Comment by jamiegeyer** [comment]
Thanks for the quick response and your work on this - it's a great tool.
