### ISSUE TITLE
Python 3 syntax for pyddq

### ISSUE THREAD

**Issue by bibwest** [FRosner/drunken-data-quality#152]
In the realease version of the package pyddq = 4.1.1. There is a print always in Python 2

File "/opt/anaconda/envs/jupyter/lib/python3.7/site-packages/pyddq/core.py", line 439
    print baos.get_output()
             ^
SyntaxError: invalid syntax

**Comment by FRosner** [comment]
Sorry to hear that you are having issues. Would you like to provide a PR?

**Comment by FRosner** [comment]
Fixed by https://github.com/FRosner/drunken-data-quality/pull/148
