### ISSUE TITLE
Provide a support for SQLContext and HiveContext

### ISSUE THREAD

**Issue by ghost** [FRosner/drunken-data-quality#24]
Currently, working with HiveContext is not very nice:

```
hc.use("default")
val t = hc.table("mytable")
Check(t)....run
```

It would be helpful to enhance the API for this.

**Comment by FRosner** [comment]
@mfsny let's create another constructor for `Check` that takes a table name, a database name and a SQL context. It should then call the named Check constructor defined in #22.

What do you think?

**Comment by ghost** [comment]
Agree, new constructor could look like this

```
Check(tableName: String, databaseName: String = "default")
``
```
