### ISSUE TITLE
Add method isConvertibleToBoolean

### ISSUE THREAD

**Issue by ghost** [FRosner/drunken-data-quality#25]
isConvertibleToBoolean should check, if the values in the column are convertible to boolean:
Parameters are
- columnName
- true value (String), default is "true"
- false value (String), default is "false"
- isCaseSensitive (Boolean), default is false

**Comment by FRosner** [comment]
Hey @mfsny. Let's do it like this that we put changes into feature branches only and code review them before we merge them. This allows also Travis to check if the code is working.

**Comment by FRosner** [comment]
@mfsny I made a couple of comments on your commit and reopened the issue. Let us create a feature branch and review the commit together.

**Comment by ghost** [comment]
@FRosner, The two new test are included now . So I am finished with this issue (or at least I think so)
