### ISSUE TITLE
Markdown report

### ISSUE THREAD

**Issue by FRosner** [FRosner/drunken-data-quality#40]
**Problem**

Currently, the only way to inspect the results is to look at the console output. However, it would be nice to also save it to a file. This should not interfere with the console output but be an additional parameter.

**Solution**

Add another parameter to the check class that tells the file to write the results to. It should be printed as markdown.

We might need to rework the way stuff is written. So the success, hint, etc. methods need to be generalized so that a check is only reporting once and console as well as markdown handles the reports differently.

**Pull Request**
#42

**Comment by FRosner** [comment]
@Gerrrr would you like to take a look at this one? It will be very useful!

**Comment by Gerrrr** [comment]
@FRosner, yes, I'd love to work on this one.
