### ISSUE TITLE
Functional dependency constraint

### ISSUE THREAD

**Issue by Gerrrr** [FRosner/drunken-data-quality#43]
**Idea**
It would be nice to check if specified columns in the data frame has [functional dependency](https://en.wikipedia.org/wiki/Functional_dependency).

**Proposed solution**
Add `hasFunctionalDependency(determinantSet: Seq[Column], dependentSet: Seq[Column])` constraint to the `Check` object, which checks that for every unique tuple of values in `determinantSet` there is only one corresponding tuple of values in `dependentSet`.

**Comment by FRosner** [comment]
@Gerrrr sounds nice. I will put it in 2.0.0.

**Comment by FRosner** [comment]
@Gerrrr what happens if the determinant and dependent columns are not distinct?
