### ISSUE TITLE
Cannot compile due to sbt dependency for slf4j-log4j12 

### ISSUE THREAD

**Issue by zhdchen** [FRosner/drunken-data-quality#46]
Always get following error meesage at running ChekTest:
`Error:scalac: bad symbolic reference. A signature in Logging.class refers to type Logger
in package org.slf4j which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling Logging.class.`

This happens even after removing following dependency from SBT and rebuild:
`-libraryDependencies += "org.slf4j" % "slf4j-log4j12" % "1.7.10" % "provided"`

**Comment by FRosner** [comment]
Thanks for reporting this @zhdchen 

Can you please try to do `sbt test` on the command line and see if it runs through? Which operating system, version of IntelliJ and version of the Scala plugin are you using?

**Comment by FRosner** [comment]
@zhdchen what is your status on this? I would like to address this problem asap. @mfsny also had this problem if I remember correctly?

**Comment by FRosner** [comment]
@zhdchen have you tried invalidating the cache in IntelliJ or removing the .idea directory and reimporting after you removed `libraryDependencies += "org.slf4j" % "slf4j-log4j12" % "1.7.10" % "provided"`?

**Comment by FRosner** [comment]
Postponing this to 2.1.0 because I received no answer so far.

**Comment by FRosner** [comment]
https://devnet.jetbrains.com/thread/473476 could be related and contain the fix.

**Comment by FRosner** [comment]
@zhdchen please try to invalidate your cache, delete the .idea folder and reimport the project. It should be fixed now.
