### ISSUE TITLE
Make run result from Runner unit test usable (+ docu)

### ISSUE THREAD

**Issue by FRosner** [FRosner/drunken-data-quality#51]
When you want to use DDQ for automated quality checks, you can also ensure the results in unit tests. We should give an example on how to write an assertion using ScalaTest for example.

**Comment by FRosner** [comment]
**Proposal** (WIP)

### Unit Tests

You can also use DDQ to write automated quality tests for your data. After running a check or a series of checks, you can inspect the results programmatically.

``` scala
def allConstraintsSatisfied(checkResult: CheckResult): Boolean =
  checkResult.constraintResults.map {
    case (constraint, ConstraintSuccess(_)) => true
    case (constraint, ConstraintFailure(_)) => false
  }.reduce(_ && _)

val results = Runner.run(Seq(check1, check2), Seq.empty)
assert(allConstraintsSatisfied(results(check1)))
assert(allConstraintsSatisfied(results(check2)))
```

If you need to manage assertions on individual constraints (e.g. enforce some of them and just want to report others), you can do so by inspecting the check result object. Let's say you want to fail the data load if the number of rows and the unique key constraints are not satisfied, but the duration constraint can be violated.

``` scala
val numRowsConstraint = Check.hasNumRowsEqualTo(3)
val uniqueKeyConstraint = Check.hasUniqueKey("id", "customerId")
val durationConstraint = Check.satisfies("duration > 0")

val check = Check(contracts)
  .addConstraint(numRowsConstraint)
  .addConstraint(uniqueKeyConstraint)
  .addConstraint(durationConstraint)

val results = Runner.run(Seq(check), Seq.empty)
val constraintResults = results(check).constraintResults
assert(constraintResults(numRowsConstraint).isInstanceOf[ConstraintSuccess])
assert(constraintResults(uniqueKeyConstraint).isInstanceOf[ConstraintSuccess])
```

**Comment by Gerrrr** [comment]
I think that it would be nice to have `allConstraintsSatisfied` as a `CheckResult` method.

**Comment by FRosner** [comment]
I thought of the same thing actually, @Gerrrr. Can you create a ticket? I also thought about conversions from constraint results to boolean but I am not sure if we will always have only two (success and failure) possible outcomes. It might be that we have some numeric outcome (like a match rate) or something like this, that is more fuzzy. I don't know. But you are right, this convenience method is nice to have.
