### ISSUE TITLE
Use Codacy and Codecov instead of Coveralls

### ISSUE THREAD

**Issue by FRosner** [FRosner/drunken-data-quality#60]
- [x] setup codacy https://www.codacy.com/app/frank_7/drunken-data-quality
- [x] setup codecov https://github.com/codecov/example-scala
- [x] replace coveralls badge by codacy and codecov badge
- [x] remove coveralls project
- [x] check GitHub integration

**Comment by JoshRosen** [comment]
I'd also consider https://codecov.io/ for code coverage; I'm using it with Databricks' `spark-redshift` library.

**Comment by FRosner** [comment]
@JoshRosen thanks for the recommendation. It will look into it. How does it compare to the coverage from codacy? Which one would you recommend?

**Comment by JoshRosen** [comment]
@FRosner, for me the big differentiator is Codecov's browser plugin for displaying coverage metrics inline in the GitHub UI. For instance, this screenshot shows inline coverage / line hit numbers displayed on a PR: 

![image](https://cloud.githubusercontent.com/assets/50748/12081114/497be334-b225-11e5-8f33-aacf22d437ee.png)

Similarly, the browser plugin can display coverage metrics in the GitHub file browser:

![image](https://cloud.githubusercontent.com/assets/50748/12081117/675e9414-b225-11e5-8470-03b0d346a161.png)

And when browsing code:

![image](https://cloud.githubusercontent.com/assets/50748/12081121/7ccb14c6-b225-11e5-836b-c1ed338466ea.png)

Codacy has some nice features, but for pure code-coverage I think Codecov wins in my book.

**Comment by FRosner** [comment]
Cool! Thanks @JoshRosen. I will go for codecov then.
