### ISSUE TITLE
Documentation for DDQ 3.0.0

### ISSUE THREAD

**Issue by FRosner** [FRosner/drunken-data-quality#81]
- [x] Wiki pages
- [x] ToC for wiki page (https://github.com/ekalinin/github-markdown-toc.go/)
- [x] Link in readme
- [x] Simplify readme by moving some of the advanced stuff to the wiki => documentation is already complex enough so I'll leave it like this for now

**Comment by Bantolomeus** [comment]
I would recommend to add the usage of multiple reporters into the wiki
