### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by FRosner** [FRosner/drunken-data-quality#94]
### Probosals

![image](https://cloud.githubusercontent.com/assets/3427394/14754151/bc210814-08d9-11e6-8024-c7f151b02189.png)

![image](https://cloud.githubusercontent.com/assets/3427394/14755914/e277aebc-08e5-11e6-9fca-8d80ec0fb860.png)

![image](https://cloud.githubusercontent.com/assets/3427394/14755942/1c5f3c94-08e6-11e6-8a60-30ac118b6dae.png)

![image](https://cloud.githubusercontent.com/assets/3427394/14755967/4bcf919a-08e6-11e6-91e0-3dc9469ecf8b.png)

![image](https://cloud.githubusercontent.com/assets/3427394/14755996/aeb9f26e-08e6-11e6-8894-bc106254f2a3.png)

**Comment by FRosner** [comment]
I like the guy with the top hat and the monocle most. What do you think, @Gerrrr? It reflects quality + drunken pretty good. Only data is missing.

**Comment by Gerrrr** [comment]
I like the owl and the guy with the hat and the monocle. Unfortunately, the problem with the latter is that he is overused everywhere.

**Comment by FRosner** [comment]
He is - but not in open source projects, is he? But I get your point.

**Comment by Kuva** [comment]
The first option to figure out what you actually want.
![option 1](https://cloud.githubusercontent.com/assets/1223076/14981157/7bb2dbc0-112d-11e6-9998-748ccfdf22bd.png)

**Comment by FRosner** [comment]
Thank you @Kuva. I'd love to have a nice logo related to data and quality, possibly also something with drinks (because the project is called drunken data quality :D).

So if we took the guy you prepared, made it a bit more interesting (colors, etc.) and maybe somehow add data or drunken, I'd be happy I guess. He already looks like good quality 👍 

But we can also have a quick chat in person if you'd like :)

**Comment by Kuva** [comment]
Option 2.2. Got lots of feedback on the original Option 2 from Aleks & implemented it. 
![ddq v2 2](https://cloud.githubusercontent.com/assets/1223076/15095181/30c916d8-14bb-11e6-97f8-e246dfc1c5e9.png)

**Comment by FRosner** [comment]
Wow that's very different from the first one!

I like the symbol, the font is a bit boring but it might not be needed anyway. Is there a special meaning behind that symbol? Colors, shapes? The small triangle?

Thanks again for your help @Kuva

**Comment by Kuva** [comment]
The triangles are data constrains, green – successfully passed, orange – failed, grey – errors.
Lines symbolise structure of a table.
Overall it's a shape of Q that's why it has that small triangular, it also refers to drunken as having a part that doesn't fit to the structure.

I haven't decided on a font yet. I'm not sure how it should look.

**Comment by FRosner** [comment]
Cool. Maybe we should change the colors a bit, now that I know the details. On the console reporter green is success, red is failure and yellow is error. But that looks very much like a traffic light. So I might take your colors instead. I'll think about it.

I don't understand the part with the lines but I really love the triangular constraints. Should've called the project triangular data quality 😄 

About the font - do we need font anyway? For me it's ok to start with a logo and we can add text if we need it. What do you think?

**Comment by Kuva** [comment]
I'll work on the colours more as well to find the right combination. It takes a while of messing with different shades to find the best combination. 

I think it's better with the font but the sign can be used without it as well. I'll make some variations so you can see for yourself.

**Comment by Kuva** [comment]
Version 3
![ddq logo v3-07](https://cloud.githubusercontent.com/assets/1223076/15376864/08c05d86-1d58-11e6-86e9-3c5fabbd30e6.png)
![ddq logo v3-09](https://cloud.githubusercontent.com/assets/1223076/15376863/08c0156a-1d58-11e6-9eca-d5a96a34a4b4.png)

**Comment by FRosner** [comment]
Amazing @Kuva! However, if we want to keep the notion of violation = red/orange and error = the other color, the purple might be a problem. It needs to look nice both on black and white backgrounds because people have black or white terminal backgrounds. I like the way it looks now a lot of I also love consistency. So what about making the yellow/orange in the latest version a bit more redish and replacing the purple color with something lighter (I think grey is not that ugly to be honest but we could also stick to the green yellow red that I am currently using.

I'm using the ascii terminal color codes (https://en.wikipedia.org/wiki/ANSI_escape_code). I use red for failures, I am using green for success and I have been using yellow for failure. However, yellow looks probably bad on white background that's why I thought about replacing it but I don't really know with what.

Hope this gives some more feedback / insight. But we don't need to necessarily stick to the colors, esp as they might change in the future and also depend on the reporter (markdown e.g. does not even have colors).

Anyway I like it a lot, the solid one even a bit more :)

What does @Gerrrr say?

![image](https://cloud.githubusercontent.com/assets/3427394/15385501/5349b72c-1da2-11e6-97b5-e8cd9a95e10d.png)

**Comment by Kuva** [comment]
@FRosner, thank you for you feedback! 
I didn't know that the logo should work on both white & black. Made some adjustments.
<img width="703" alt="ddq logo v3 2" src="https://cloud.githubusercontent.com/assets/1223076/15405538/95e91720-1e02-11e6-9777-fd7b49f15604.png">

**Comment by FRosner** [comment]
No sorry. Not the logo has to work (although it's nice if it does, but the colors in the reporter have to. I can show you how it looks.

**Comment by Kuva** [comment]
@FRosner The colours of the logo doesn't have to be the same ones as you use in the reporter. It's good if you can but it's not obligatory.

**Comment by FRosner** [comment]
Looking at your last proposals @Kuva, I like the last row most. And it actually works both on black and white backgrounds 👍 

Also it is not so intrusive and looks very professional.

**Comment by FRosner** [comment]
So are we going to go for the last one, @Kuva? How do you want to share it? Do you want to upload it at openclipart?

**Comment by Kuva** [comment]
Sure, let's settle on the last logo. What format do you need: png or svg? If png, then I need to know the size. 
Openclipart doesn't look like a place to upload a logo.

**Comment by FRosner** [comment]
You're the expert @Kuva. Tell me where you want to put it. I'd put it somewhere where I can download it in different sizes. I'd like to store it as SVG, so we can resize it later.

But I guess we can at least put it in git. Do you want to create a pull request or do you want to send it to me via mail / upload it to whatever site you'd like and I do it.

Thanks again!

**Comment by FRosner** [comment]
https://github.com/FRosner/drunken-data-quality/blob/master/logo/DDQ.svg
